name: medongosupport
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #UI PLUGINS
  cupertino_icons: ^1.0.2   # Use with the CupertinoIcons class for iOS style icons.
  percent_indicator: ^4.2.3 #Show the Percentage Progress Bar
  im_stepper: ^1.0.1+1 #Active Step for Dot Controller
  dynamic_height_grid_view: ^0.0.3 #GridView used in Category
  fluttertoast: ^8.0.9 #SHOWS TOAST MESSAGES
  loading_overlay: ^0.3.0 #CREATES A OVERLAY WHEN SOMETHING IS LOADING IN THE BG
  loading_animations: ^2.2.0
  chips_choice: ^3.0.0
  auto_size_text: ^3.0.0 #RESIZES THE TEXT BASED ON LAYOUT ORIENTATION
  image: ^4.0.17
  #expandable_fab_menu: ^0.0.1
  #flutter_expandable_fab: ^1.7.1
  timer_count_down: ^2.2.2
  scroll_date_picker: ^3.7.1
  progress_stepper: ^1.0.0
  dropdown_search: ^5.0.6 #DROPDOWN SEARCH USED TO SEARCH A USER
  animated_bottom_navigation_bar: ^1.1.0 #UPDATED
  cached_network_image: ^3.2.1 #CACHES NETWORK IMAGES TO AVOID RE-LOADING OF DATA
  shimmer: ^2.0.0 #GIVES SHIMMER EFFECT TO ANY SPECIFIED WIDGET
  flutter_easyloading: ^3.0.5 #PROVIDES LOADING ANIMATIONS
  carousel_slider: ^4.1.1 #CAROUSEL SLIDER TO DISPLAYS CAROUSELS - ALTERNATIVE 1
  fl_chart: ^0.60.0 #CHARTS VIEW
  mrx_charts: ^0.1.3 #CHARTS VIEW
  flutter_carousel_slider: ^1.1.0 #CAROUSEL SLIDER TO DISPLAYS CAROUSELS - ALTERNATIVE 2


  #UTILITIES PLUGINS
  permission_handler: ^10.2.0 #This plugin is for taking permission to record audio
  path_provider: ^2.0.14 #This plugin is for taking permission to store files to local storage
  app_settings: ^4.2.0 #OPENS APP SETTINGS
  location: ^5.0.0-dev.8 #ALLOWS THE USER TO DEAL WITH LOCATION
  image_picker: ^0.8.7+5
  file_picker: ^5.3.0
  image_cropper:
  #document_scanner_flutter: any #DOCUMENT SCANNER
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  path: ^1.8.0
  readmore: ^2.2.0
  video_player: ^2.6.1
  just_audio:
  assets_audio_player: ^3.0.6
  image_gallery_saver: ^2.0.1 #PLUGIN TO TAKE SCREENSHOT
  url_launcher: ^6.1.10 #USER FOR LAUNCHING URLS
  #flutter_inappwebview: ^5.7.2+3 #LOADS IN APP WEB VIEW - USED IN AUTH
  http: ^0.13.5 #DEALING WITH HTTP CALLS
  intl: ^0.18.0 #USED IN PARSING DATES AND OTHER VALUES
  open_filex: ^4.2.2 #CALLS NATIVE APPS TO OPEN FILES - WORKS ON BOTH ANDROID AND iOS
  mime: ^1.0.4 #WORKS WITH MIME TYPE DEFINITIONS FOR PROCESSING MULTIPART MEDIA TYPES
  mime_type: ^1.0.0 #FETCHES MIME TYPE
  connectivity_plus: ^4.0.0 #CHECKS INTERNET STATUS OF THE DEVICE
  ffmpeg_kit_flutter: ^5.1.0 #USED FOR CUTTING AUDIOS - NEW
  flutter_secure_storage: ^8.0.0
  restart_app: ^1.2.1



  #AMAZON AWS AMPLIFY
  #amplify_auth_cognito: any
  #amplify_authenticator: ^1.0.0
  #amplify_flutter: ^1.0.0
  #amplify_storage_s3: ^1.0.0
  #aws_common: ^0.5.0+1

  #SHOULD BE REMOVED IN THE FUTURE.
  #aws3_bucket: ^0.0.8


  #FACE DETECTION AND RECORDING
  #google_ml_kit: ^0.14.0    #for face detection
  google_mlkit_face_detection: ^0.6.0 #for face detection
  camera: ^0.10.5 #for the camera preview,image capturing and video recording

  #AUDIO RECORDING
  record: ^4.4.4   # This plugin is for recording the audio file
  translator: ^0.1.7   # This translator is for translate audio to text
  sizer: ^2.0.15
  audioplayers: ^4.0.1

  #FIREBASE
  firebase_storage: ^11.1.2 #This plugin is for storing the audio, video, image files in database
  cloud_firestore: ^4.5.0   #for firebase database support
  firebase_core: ^2.11.0 # This plugin is for initializing the app as a firebase app
  firebase_auth:

  #GET ENVIRONMENT
  get: ^4.6.5 #MAIN GET PLUGIN FOR STATE, NAVIGATION AND DEPENDENCY MANAGEMENT
  get_storage: ^2.0.3 #WORKS SIMILAR TO PREFERENCES WITH MORE ACCURACY AND SPEED

  #SENSOR PLUGIN
  light: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  assets:
    - assets/imagesItachyonSupport/
    - assets/imagesPreconsult/

  module:
    androidX: true
    androidPackage: com.axiphyl.medongosupport
    iosBundleIdentifier: com.axiphyl.medongosupport
